name: Feature request
description: Suggest an idea for this project
title: '[Title here. keep it short]'
labels: ['feature']
assignees:
    - thewh1teagle
body:
    - type: markdown
      attributes:
          value: |
              💚💜 Thank you for interest. ❤️💛
              *Please prioritize checking existing issues first*. [bugs](https://github.com/thewh1teagle/sherpa-rs/issues?q=is:issue+label:bug+)
              I will repay with higher-quality code.
              
    - type: textarea
      id: describe-the-feature
      attributes:
          label: Describe the feature
          description: Also tell us why you think it useful
          placeholder: Description...
      validations:
          required: true