/*
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/kokoro-multi-lang-v1_0.tar.bz2
tar xf kokoro-multi-lang-v1_0.tar.bz2
rm kokoro-multi-lang-v1_0.tar.bz2
cargo run --example tts_kokoro

For Chinese:
    let sid = 50;
    let text = "中英文语音合成测试。This is generated by next generation Kaldi using Kokoro without Misaki. 你觉得中英文说的如何呢？";
*/
pub use sherpa_rs::tts::{ KokoroTts, KokoroTtsConfig };

fn main() {
    let config = KokoroTtsConfig {
        model: "./kokoro-multi-lang-v1_0/model.onnx".to_string(),
        voices: "./kokoro-multi-lang-v1_0/voices.bin".into(),
        tokens: "./kokoro-multi-lang-v1_0/tokens.txt".into(),
        data_dir: "./kokoro-multi-lang-v1_0/espeak-ng-data".into(),
        dict_dir: "./kokoro-multi-lang-v1_0/dict".into(),
        lexicon: "./kokoro-multi-lang-v1_0/lexicon-us-en.txt,./kokoro-multi-lang-v1_0/lexicon-zh.txt".into(),
        length_scale: 1.0,
        ..Default::default()
    };
    let mut tts = KokoroTts::new(config);

    let sid = 0;
    let text = "This is generated by next generation Kaldi using Kokoro without Misaki.";
    let audio = tts.create(&text, sid, 1.0).unwrap();
    sherpa_rs::write_audio_file("audio.wav", &audio.samples, audio.sample_rate).unwrap();
    println!("Created audio.wav")
}
