/*
wget https://huggingface.co/csukuangfj/vits-ljs/resolve/main/vits-ljs.onnx
wget https://huggingface.co/csukuangfj/vits-ljs/resolve/main/lexicon.txt
wget https://huggingface.co/csukuangfj/vits-ljs/resolve/main/tokens.txt
cargo run --example tts_vits --features="tts"
*/
pub use sherpa_rs::tts::{ VitsTts, VitsTtsConfig };

fn main() {
    let config = VitsTtsConfig {
        model: "./vits-ljs.onnx".into(),
        lexicon: "./lexicon.txt".into(),
        tokens: "./tokens.txt".into(),
        length_scale: 1.0,
        ..Default::default()
    };
    let mut tts = VitsTts::new(config);
    let sid = 0;
    let audio = tts.create("Hello! This audio generated by onnx model!", sid, 1.0).unwrap();
    sherpa_rs::write_audio_file("audio.wav", &audio.samples, audio.sample_rate).unwrap();
    println!("Created audio.wav")
}
